### ISSUE TITLE
JOSS review - Community guidelines

### ISSUE THREAD

**Issue by craig-willis** [terminological/dtrackr#11]
Review issue: https://github.com/openjournals/joss-reviews/issues/4707
Branch reviewed: release-0.2.4

**Problem**
JOSS requires clear guidelines for third-parties wishing to contribute to the software.  See [Community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) for more information.

A common approach is to add a [CONTRIBUTING](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file to the repository.

**Comment by craig-willis** [comment]
Just noticed the `.github/CONTRIBUTING.md` and that it appears on the package website. I'm accustomed to seeing this in the repo root, but expect this meets the JOSS requirement.

**Comment by robchallen** [comment]
Thanks. I understand re the comments being too personal. I have revised the CONTRIBUTING section based on a template I found below.

This Code of Conduct is adapted from the [Contributor Covenant][homepage], version 1.4, available at [http://contributor-covenant.org/version/1/4][version]

**Comment by robchallen** [comment]
I've left the location of the contributing guideline as it is in .github/CONTRIBUTING.md, as in that location it is automatically linked to from the new issues page on GitHub.

To address your other comment about the style of the documentation i've:

- [updated the contents of the CONTRIBUTING.md](https://terminological.github.io/dtrackr/CONTRIBUTING.html) 
- [rewritten much of the README.md](https://terminological.github.io/dtrackr/index.html)

Please take a look and see what you think.

**Comment by craig-willis** [comment]
Looks good. Just a note: it looks like a `CODE_OF_CONDUCT.md` in the repo root will display a link under the About section (e.g., https://github.com/github/docs). I wish they did this with with `CONTRIBUTING.md` as well.
