### ISSUE TITLE
JOSS Review - Function Documentation for landscape

### ISSUE THREAD

**Issue by debruine** [terminological/dtrackr#22]
Review issue: openjournals/joss-reviews#4707
Branch reviewed: main

The documentation for [`landscape()`](https://terminological.github.io/dtrackr/reference/landscape.html) is quite sparse. It could use an example. My first attempt to guess failed (I tried `landscape(std_size$A4$height)`) and that was only after I'd read the documentation for `std_size`. You might link to `std_size`, as it's not immediately obvious that this is an object built into dtrackr. 

It's also not obvious when or where you'd use this function. It doesn't take any dtrackr objects as an argument, so I first assumed it was an option that needed to be set before running `save_dot()`, but that didn't work. I noticed it outputs a size list, so then I tried the code below, but that doesn't seem to produce any difference in orientation:

```
x <- save_dot("digraph {A->B}", tempfile(), 
              size = landscape(std_size$half), 
              formats = "png")
browseURL(x$paths$png)
```

**Comment by robchallen** [comment]
Apologies. The landscape function did do something useful in an earlier iteration of `dtrackr`, and resulted in pdf and png formats being rotated, but the functionality got taken out as was not really core and the dependencies it introduced were complex.

To address this specific issue I've taken out the `landscape()` function. 

What I have done instead is extend the `std_size` definitions to include some landscape style paper dimensions. I've linked to the `std_size` documentation from [flowchart()](https://terminological.github.io/dtrackr/reference/flowchart.html) to make this more explicit, and I've updated the `std_size` documentation to make it clear what it is, what values are available, and what it is for.

**Comment by robchallen** [comment]
std_size documentation is at https://terminological.github.io/dtrackr/reference/std_size.html

Please close this issue if you are happy with this outcome.

**Comment by robchallen** [comment]
@debruine Is there anything else you need me to take a look or are you happy to sign off on this and the [other open issue](#17)
All the best,

**Comment by debruine** [comment]
Sorry, missed this in my notifications! That looks good.
