### ISSUE TITLE
dpi of flowcharts

### ISSUE THREAD

**Issue by dvaiman** [terminological/dtrackr#35]
I use the `p_get_as_dot()` and then `save_dot()` to save the flowchart as a .png or .svg but think the quality of the image is not the best. Is there a way to improve the quality?

**Comment by robchallen** [comment]
When you call have a tracked df, you can use:

```
df %>% dtrackr::flowchart( 
   filename = "my-flowchart", 
   formats = c("png","svg"),  
   maxWidth = <width in inches>,
   maxHeight = <height in inches>
)
```

(N.b. you can do the same thing with p_get_as_dot() and save_dot() its just they were intended really for people that wanted to edit the dot output before rendering it.)

The default values of both `flowchart()` and `save_dot()` try and fit the flowchart into a half A4 page. If your flowchart is very wide or tall dtrackr may be shrinking it excessively.

If your flowchart is large `maxWidth` and `maxHeight` will need to be increased. 

SVG doesn't have a DPI as such so you should be able to zoom in / resize SVG output in a SVG editor regardless of the size.

The PNG output has a DPI hard coded to 300, so if it is too pixelated increasing the width / height in inches is the only way to go, but obviously the PNG file size will get larger.

**Comment by dvaiman** [comment]
Was looking for something like ggplots ggsave function... but this was even easier. Thanx.
